### PR TITLE
Add "pinned" feature

### PR DESCRIPTION
**Pull request by cole-h**
This allows you to choose between the pinned, hardcoded nix-store and nix-build paths, and runtime PATH resolution.

### CODE REVIEW

**Comment by Hoverbear** [comment]
In what situations do we want `pinned` on?

**Comment by grahamc** [comment]
Basically anything built by nix and used as a nix closure should use "pinned" so it carries Nix in its runtime closure.

**Review by Hoverbear — APPROVED** [review]

**Comment by Hoverbear** [comment]
Should `pinned` be default then?

**Comment by grahamc** [comment]
Yeah, imho, pinned should probably be default. Can discuss more, though :).

**Pull request merged**
